version: '3.8'

services:
  pg:
    container_name: dev_pg
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: justpass
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - dev_pg_data:/var/lib/postgresql/data

  pgadmin4:
    container_name: dev_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "5050:80"
    volumes:
      - dev_pgadmin:/var/lib/pgadmin

volumes:
  dev_pg_data:
    driver: local
  dev_pgadmin:
    driver: local
